### ISSUE TITLE
Can't render grafana 7.2

### ISSUE THREAD

**Issue by c33howard** [Cqoicebordel/webslice-plasmoid#27]
Something about grafana 7.2 causes a render failure.  Compare the following url in chrome/firefox/konqueror/web browser plasmoid vs web slice:

https://play.grafana.org/d/000000012/grafana-play-home?orgId=1

My internal (ie not internet accessible) grafana deploy of 5.x rendered fine in web slice.

**Comment by Cqoicebordel** [comment]
So, a couple of things : 
* I don't see any differences between Chromium 87 and Webslice for the link you provided.
* Sadly, the version of Chromium used by Qt (and so, Webslice) is usually old. On my Kubuntu 20.04, it's Chrome 69. It probably will depend of your system. you can go to https://www.whatsmyua.info/ with Webslice to know for sure (there may be better method to know, but that's the easiest I know)(of course, only if you haven't changed you User-Agent in the settings).

So I think the issue is the version of Chromium supported by Grafana. https://grafana.com/docs/grafana/latest/installation/requirements/ indicates that it follows the current versions, so no love for older version :/  
Sadly I can't do anything. You can try changing your user-agent string, in case the support is blocked dumbly, but I doubt it'll do anything.  
All in all, it's dependent on the version of Chromium, and Qt :/

**Comment by c33howard** [comment]
Interesting.  On my system (also Kubuntu 20.04), my UA is reported as Safari 10.  I wonder why Qt on my system is using a different engine.

My homedir is *old*.  I wouldn't be shocked to find I've got some stale config in there somewhere.

Thanks for the pointer though.  That's probably enough for me to track down what's going on.  I'll resolve, since it seems like this is a Qt thing.
