### ISSUE TITLE
Add an option to pin the popup

### ISSUE THREAD

**Issue by maikol-solis** [Cqoicebordel/webslice-plasmoid#28]
If the user selects "Display a button..." to create a popup inside the panel, it could be useful if this popup could be pinned. 

This way the user could work in another app while the popup is open. 

Thanks.

**Comment by Cqoicebordel** [comment]
That's an excellent idea !

I found a way to implement it, now I have to think about how to show it to users. I'm leaning toward a checkbox in the settings, but I still have to think on it.

So, it will come in the short term (less than 2 weeks, I'm guessing), but not today :)

**Comment by maikol-solis** [comment]
Thank you very much. 

It could be also a thumbtack icon on the top right of the widget, to pin it and unpin it easily.  For example 

![](https://www.ubuntupit.com/wp-content/uploads/2020/07/kde_connect.jpg)

Whatever solution you choose it will be fantastic. 

Best.

**Comment by Cqoicebordel** [comment]
Yeah, I thought of that, the issue is that the popup doesn't show any UI, it shows only the website. Having a white horizontal bar just to host the pin button might not be ideal. If I can create just the pin button in the corner, that would indeed be perfect, but I'm not sure yet if that's possible or not.

It depends on the time I'm willing to take to search how to implement it too :D 

In any case, it will be done :)

**Comment by maikol-solis** [comment]
Thanks. I'll be looking forward to it.

**Comment by Cqoicebordel** [comment]
Just pushed a fix for it.

I won't release it on the KDE store yet, as I wait for a translations. Will be in a couple days, prolly.

**Comment by maikol-solis** [comment]
Fantastic! Superfast though. Thanks.

**Comment by Cqoicebordel** [comment]
Just FYI, if you waited for it, it's released on the store. So just using the update feature in KDE should work now :)

**Comment by maikol-solis** [comment]
Thanks a lot! It seems perfect. Kudos!
