### ISSUE TITLE
A version that works with debian stable version ?

### ISSUE THREAD

**Issue by Utopism** [Cqoicebordel/webslice-plasmoid#30]
Hi,
The stable version of debian provides this qtquick version : 
qml-module-qtquick2:amd64                     5.11.3-4
Can I find a way to have the plasmoid to work in this environment ?
It seems that there was a direct jump from QtQuick 2.7 to QtQuick 2.12 between version 1 and 2 of the plasmoid.

**Comment by Cqoicebordel** [comment]
Yes, it's a good question, but I think the answer won't be to your liking :  
I seem to remember that when switching from the 1.0 to the 2.0 of this plasmoid, I had to rewrite most of it, because the WebEngine used was switched from Webkit to Chromium internally (from https://doc.qt.io/qt-5/qml-qtwebview-webview.html to http://doc.qt.io/qt-5/qml-qtwebengine-webengineview.html, if you want more details).

Which means that all the features that I implemented in the 2.x branch can't be implemented in the 1.x branch, because the APIs used were just not available in WebView (vs. WebEngineView now).

So, the short answer is that on systems with older version than Plasma 5.18, the current release is the 1.01, and it will sadly stay this way.  

I hope I answered your question. If you have a followup, don't hesitate, all those versions numbers make me dizzy, so I could have misunderstood something :)

**Comment by Utopism** [comment]
Hi, thanks for your detailed reply, and sorry to comment only now.
* My issue with debian is that current stable version of QtQuick Qml is 2.11
VS 2.12 for V2 of your magnificent plasmoid :-)
* As I can see, QtWebEngine exists since at least V5.5
https://doc.qt.io/archives/qt-5.5/qml-qtwebengine-webengineview.html
* Qt V5.11 provides WebEngineView  **V1.7**
https://doc.qt.io/archives/qt-5.11/qml-qtwebengine-webengineview.html
* Qt V5.12 provides WebEngineView  **V1.8**
https://doc.qt.io/qt-5.12/qml-qtwebengine-webengineview.html
So can it be feasible to have a compatible version with **QtQuick V2.11**, with no trouble about compatibility issues ?
On the debian side next stable version provides Qt V5.14 hence QtQuick V2.12, but this version will be available in a looonng time. And I haven't found some way to have a more recent version of these libraries.
Merci pour votre attention.

**Comment by Cqoicebordel** [comment]
Maybe it could work. I don't know.  
The big issue would be that I can't test anything, as I don't have a Debian running.

So the easiest way would be for you to do and test it :)

If you have the plasmoid installed, go to `/home/cqoicebordel/.local/share/plasma/plasmoids/cqcb.plasma.webslice/` (let's call it "main folder")  
There you'll find all the files you need to edit in `contents/ui/`
Here, you'll have to first edit the `main.qml`. The library versions are indicated near the top of the file.

I'm guessing you'll have to edit it to look like this : 
```qml
import QtQuick 2.11
import QtWebEngine 1.7
import QtQuick.Layouts 1.10
import QtQuick.Controls 2.11
import org.kde.plasma.plasmoid 2.0
import org.kde.plasma.components 2.0 as PlasmaComponents
import org.kde.plasma.core 2.0 as PlasmaCore
import QtQml 2.11

import "../code/utils.js" as ConfigUtils
```
I have no idea what the correct values are, so you'll probably have to fiddle with those.  
Then, to test it, you go to the main folder, and execute `plasmoidviewer -a .` (I trust you know how to install plasmoidviewer if it isn't installed yet).  
If there isn't any error in the plasmoid (not in the console, we don't care about errors there) and if it's working, you are almost good to go. You can close the plasmoidviewer window, and edit the rest of the `.qml` files, to set the same version as in the main. Just be careful to not increase the version numbers : if you have `QtQuick.Controls 2.XX` working in main, don't switch `QtQuick.Controls 1.4` (in `ConfigMultipleURLs.qml`) to 2.XX. Keep it at 1.4, it's on purpose. The same thing might happen in other cases too, so be careful.

Once you have done all that, you can restart plasmashell, and put the plasmoid on your desktop (hopefully :) )

Again, if you have other questions, don't hesitate to ask !

**Comment by Utopism** [comment]
Merci for all these informations. I'll test it.
